name: Packer Build (After Merge)

on:
  push:
    branches:
      - main

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install AWS CLI
        run: |
          sudo apt update
          sudo apt install -y awscli

      - name: Configure AWS CLI
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_GITHUB_ACCESS_KEY }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_GITHUB_SECRET_KEY }}
          aws configure set region ${{ secrets.AWS_REGION }}

      - name: Install Packer
        run: |
          sudo apt update && sudo apt install -y unzip
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt update && sudo apt install -y packer

      - name: Install and Set up JDK21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Run Integration Tests
        run: |
          cd ./TestSuite/ && mvn test

      - name: Build Application Artifact
        run: |
          cd webapp
          mvn clean package -DskipTests
          mkdir -p packer/app
          cp target/webapp-0.0.1-SNAPSHOT.jar ../packer/app/

      - name: Packer Build (Create Custom Image)
        run: |
          cd packer
          packer build \
            -var "instance_type=${{ vars.AWS_INSTANCE_TYPE }}" \
            -var "region=${{ vars.AWS_REGION }}" \
            -var "profile=${{ vars.AWS_PROFILE }}" \
            -var "ssh_username=${{ vars.AWS_SSH_USERNAME }}" \
            -var "USERNAME=${{ secrets.username }}" \
            -var "MYSQL_PWD=${{ secrets.MYSQL_PWD }}" \
            aws-ubuntu.pkr.hcl
